import type { NextPage } from 'next'
import Head from 'next/head'
import { ContactForm, HeroTwo } from '../components'

const Contact: NextPage = () => {
    return(
        <div className="p-2">

            <Head>
                <title> Hubungi Kami | PT BSL </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HeroTwo />

            <ContactForm />
            
        </div>
    )
}

export default Contact
